import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topbar from "./topbar/topbar";
import ReduxProvider from "../store/Provider";
import AmplifyProvider from "../components/AmplifyProvider";
import Footer from "./footer/components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <>
          <AmplifyProvider>
            <ReduxProvider>
              <Topbar />
              {children}
              <Footer />
            </ReduxProvider>
          </AmplifyProvider>
        </>
      </body>
    </html>
  );
}
