name: 🚀 Deploy Frontend on Dev Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/online-consultant-frontend
            git pull origin main
            npm install
            npm run build
            pm2 delete frontend-https || true
            pm2 start server.js --name frontend-https